[2023-10-05T10:23:38.079+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: YouTube_Post_Dag.processed_data_insert_task manual__2023-10-05T10:21:08.949562+00:00 [queued]>
[2023-10-05T10:23:38.094+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: YouTube_Post_Dag.processed_data_insert_task manual__2023-10-05T10:21:08.949562+00:00 [queued]>
[2023-10-05T10:23:38.096+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-10-05T10:23:38.120+0000] {taskinstance.py:1382} INFO - Executing <Task(YouTubeProcessDataTableOperator): processed_data_insert_task> on 2023-10-05 10:21:08.949562+00:00
[2023-10-05T10:23:38.150+0000] {standard_task_runner.py:57} INFO - Started process 749 to run task
[2023-10-05T10:23:38.158+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'YouTube_Post_Dag', 'processed_data_insert_task', 'manual__2023-10-05T10:21:08.949562+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/youTube_video_data_dag.py', '--cfg-path', '/tmp/tmpwcfeipey']
[2023-10-05T10:23:38.167+0000] {standard_task_runner.py:85} INFO - Job 100: Subtask processed_data_insert_task
[2023-10-05T10:23:38.295+0000] {task_command.py:415} INFO - Running <TaskInstance: YouTube_Post_Dag.processed_data_insert_task manual__2023-10-05T10:21:08.949562+00:00 [running]> on host bdf8a93b58be
[2023-10-05T10:23:38.469+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='YouTube_Post_Dag' AIRFLOW_CTX_TASK_ID='processed_data_insert_task' AIRFLOW_CTX_EXECUTION_DATE='2023-10-05T10:21:08.949562+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-05T10:21:08.949562+00:00'
[2023-10-05T10:23:38.474+0000] {youTube_process_data_table_operator.py:27} INFO - Executing CustomMySqlOperator with data from task: data_transformation_task
[2023-10-05T10:23:38.794+0000] {sql.py:274} INFO - Executing: CREATE TABLE IF NOT EXISTS youtube_posts(id INT AUTO_INCREMENT PRIMARY KEY,title VARCHAR(255), view_count INT, like_count INT, comment_count INT, favorite_count INT, duration VARCHAR(255), published_at DATETIME DEFAULT NULL, published_date DATETIME DEFAULT NULL, published_time DATETIME DEFAULT NULL,)
[2023-10-05T10:23:38.811+0000] {base.py:73} INFO - Using connection ID 'mysql_connection' for task execution.
[2023-10-05T10:23:38.826+0000] {base.py:73} INFO - Using connection ID 'mysql_connection' for task execution.
[2023-10-05T10:23:38.854+0000] {sql.py:418} INFO - Running statement: CREATE TABLE IF NOT EXISTS youtube_posts(id INT AUTO_INCREMENT PRIMARY KEY,title VARCHAR(255), view_count INT, like_count INT, comment_count INT, favorite_count INT, duration VARCHAR(255), published_at DATETIME DEFAULT NULL, published_date DATETIME DEFAULT NULL, published_time DATETIME DEFAULT NULL,), parameters: None
[2023-10-05T10:23:38.857+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/youTube_process_data_table_operator.py", line 31, in execute
    self.create_table(context)
  File "/opt/airflow/plugins/youTube_process_data_table_operator.py", line 45, in create_table
    create_task.execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/home/airflow/.local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/airflow/.local/lib/python3.8/site-packages/MySQLdb/connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1")
[2023-10-05T10:23:38.879+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=YouTube_Post_Dag, task_id=processed_data_insert_task, execution_date=20231005T102108, start_date=20231005T102338, end_date=20231005T102338
[2023-10-05T10:23:38.900+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 100 for task processed_data_insert_task ((1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1"); 749)
[2023-10-05T10:23:38.944+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-05T10:23:38.988+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
