[2023-10-05T15:29:16.886+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: YouTube_starbucks_Dag.save_starbucks_task manual__2023-10-05T15:29:08.574013+00:00 [queued]>
[2023-10-05T15:29:16.900+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: YouTube_starbucks_Dag.save_starbucks_task manual__2023-10-05T15:29:08.574013+00:00 [queued]>
[2023-10-05T15:29:16.902+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-10-05T15:29:16.919+0000] {taskinstance.py:1382} INFO - Executing <Task(StarbucksDataTableOperator): save_starbucks_task> on 2023-10-05 15:29:08.574013+00:00
[2023-10-05T15:29:16.929+0000] {standard_task_runner.py:57} INFO - Started process 259 to run task
[2023-10-05T15:29:16.936+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'YouTube_starbucks_Dag', 'save_starbucks_task', 'manual__2023-10-05T15:29:08.574013+00:00', '--job-id', '109', '--raw', '--subdir', 'DAGS_FOLDER/youtube_starbucks_dag.py', '--cfg-path', '/tmp/tmp_u7bczzi']
[2023-10-05T15:29:16.942+0000] {standard_task_runner.py:85} INFO - Job 109: Subtask save_starbucks_task
[2023-10-05T15:29:17.021+0000] {task_command.py:415} INFO - Running <TaskInstance: YouTube_starbucks_Dag.save_starbucks_task manual__2023-10-05T15:29:08.574013+00:00 [running]> on host 83a26c877c38
[2023-10-05T15:29:17.139+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='YouTube_starbucks_Dag' AIRFLOW_CTX_TASK_ID='save_starbucks_task' AIRFLOW_CTX_EXECUTION_DATE='2023-10-05T15:29:08.574013+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-05T15:29:08.574013+00:00'
[2023-10-05T15:29:17.143+0000] {starbucks_data_table_operator.py:27} INFO - Executing CustomMySqlOperator with data from task: extract_chanel_data_task
[2023-10-05T15:29:17.159+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/starbucks_data_table_operator.py", line 28, in execute
    reddit_comment_csv = context['task_instance'].xcom_pull(key='reddit_post_comment_raw_data', task_ids=['extract_post_comment_task'])[0]
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 794, in __getitem__
    raise IndexError(key) from None
IndexError: 0
[2023-10-05T15:29:17.174+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=YouTube_starbucks_Dag, task_id=save_starbucks_task, execution_date=20231005T152908, start_date=20231005T152916, end_date=20231005T152917
[2023-10-05T15:29:17.459+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 109 for task save_starbucks_task (0; 259)
[2023-10-05T15:29:17.515+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-05T15:29:17.545+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
