[2023-10-05T15:32:14.834+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: YouTube_starbucks_Dag.save_starbucks_task manual__2023-10-05T15:32:05.722830+00:00 [queued]>
[2023-10-05T15:32:14.854+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: YouTube_starbucks_Dag.save_starbucks_task manual__2023-10-05T15:32:05.722830+00:00 [queued]>
[2023-10-05T15:32:14.855+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-10-05T15:32:14.873+0000] {taskinstance.py:1382} INFO - Executing <Task(StarbucksDataTableOperator): save_starbucks_task> on 2023-10-05 15:32:05.722830+00:00
[2023-10-05T15:32:14.884+0000] {standard_task_runner.py:57} INFO - Started process 318 to run task
[2023-10-05T15:32:14.890+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'YouTube_starbucks_Dag', 'save_starbucks_task', 'manual__2023-10-05T15:32:05.722830+00:00', '--job-id', '111', '--raw', '--subdir', 'DAGS_FOLDER/youtube_starbucks_dag.py', '--cfg-path', '/tmp/tmphp0a380s']
[2023-10-05T15:32:14.907+0000] {standard_task_runner.py:85} INFO - Job 111: Subtask save_starbucks_task
[2023-10-05T15:32:14.981+0000] {task_command.py:415} INFO - Running <TaskInstance: YouTube_starbucks_Dag.save_starbucks_task manual__2023-10-05T15:32:05.722830+00:00 [running]> on host 83a26c877c38
[2023-10-05T15:32:15.088+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='YouTube_starbucks_Dag' AIRFLOW_CTX_TASK_ID='save_starbucks_task' AIRFLOW_CTX_EXECUTION_DATE='2023-10-05T15:32:05.722830+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-05T15:32:05.722830+00:00'
[2023-10-05T15:32:15.090+0000] {starbucks_data_table_operator.py:27} INFO - Executing CustomMySqlOperator with data from task: extract_chanel_data_task
[2023-10-05T15:32:15.107+0000] {sql.py:274} INFO - Executing: CREATE TABLE  IF NOT EXISTS organization_table(id INT AUTO_INCREMENT PRIMARY KEY, social_media_platform VARCHAR(255),description TEXT, display_name VARCHAR(255),image VARCHAR(255),subscribers INT,title VARCHAR(255),url VARCHAR(255))
[2023-10-05T15:32:15.566+0000] {base.py:73} INFO - Using connection ID 'mysql_connection' for task execution.
[2023-10-05T15:32:15.577+0000] {base.py:73} INFO - Using connection ID 'mysql_connection' for task execution.
[2023-10-05T15:32:15.742+0000] {sql.py:418} INFO - Running statement: CREATE TABLE  IF NOT EXISTS organization_table(id INT AUTO_INCREMENT PRIMARY KEY, social_media_platform VARCHAR(255),description TEXT, display_name VARCHAR(255),image VARCHAR(255),subscribers INT,title VARCHAR(255),url VARCHAR(255)), parameters: None
[2023-10-05T15:32:15.913+0000] {sql.py:427} INFO - Rows affected: 0
[2023-10-05T15:32:15.930+0000] {logging_mixin.py:151} INFO - mysql_connection
[2023-10-05T15:32:16.550+0000] {logging_mixin.py:151} INFO -              title               display_name  ...  description image
0  Starbucks Music  @starbucksmusiccollection  ...          NaN   NaN

[1 rows x 6 columns]
[2023-10-05T15:32:16.555+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/starbucks_data_table_operator.py", line 32, in execute
    self.intermediate_ingestion(context, starbucks_data_csv)
  File "/opt/airflow/plugins/starbucks_data_table_operator.py", line 62, in intermediate_ingestion
    df.to_sql(con=engine, name=self.table_name, if_exists='extend', index=False , chunksize=3000)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 2878, in to_sql
    return sql.to_sql(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 759, in to_sql
    raise ValueError(f"'{if_exists}' is not valid for if_exists")
ValueError: 'extend' is not valid for if_exists
[2023-10-05T15:32:16.605+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=YouTube_starbucks_Dag, task_id=save_starbucks_task, execution_date=20231005T153205, start_date=20231005T153214, end_date=20231005T153216
[2023-10-05T15:32:16.638+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 111 for task save_starbucks_task ('extend' is not valid for if_exists; 318)
[2023-10-05T15:32:16.697+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-05T15:32:16.727+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
