[2023-10-05T15:35:04.939+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: YouTube_starbucks_Dag.save_starbucks_task manual__2023-10-05T15:33:49.324302+00:00 [queued]>
[2023-10-05T15:35:04.953+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: YouTube_starbucks_Dag.save_starbucks_task manual__2023-10-05T15:33:49.324302+00:00 [queued]>
[2023-10-05T15:35:04.955+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-10-05T15:35:04.977+0000] {taskinstance.py:1382} INFO - Executing <Task(StarbucksDataTableOperator): save_starbucks_task> on 2023-10-05 15:33:49.324302+00:00
[2023-10-05T15:35:04.988+0000] {standard_task_runner.py:57} INFO - Started process 383 to run task
[2023-10-05T15:35:04.994+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'YouTube_starbucks_Dag', 'save_starbucks_task', 'manual__2023-10-05T15:33:49.324302+00:00', '--job-id', '115', '--raw', '--subdir', 'DAGS_FOLDER/youtube_starbucks_dag.py', '--cfg-path', '/tmp/tmpb7zgqumj']
[2023-10-05T15:35:05.000+0000] {standard_task_runner.py:85} INFO - Job 115: Subtask save_starbucks_task
[2023-10-05T15:35:05.161+0000] {task_command.py:415} INFO - Running <TaskInstance: YouTube_starbucks_Dag.save_starbucks_task manual__2023-10-05T15:33:49.324302+00:00 [running]> on host 83a26c877c38
[2023-10-05T15:35:05.288+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='YouTube_starbucks_Dag' AIRFLOW_CTX_TASK_ID='save_starbucks_task' AIRFLOW_CTX_EXECUTION_DATE='2023-10-05T15:33:49.324302+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-05T15:33:49.324302+00:00'
[2023-10-05T15:35:05.292+0000] {starbucks_data_table_operator.py:27} INFO - Executing CustomMySqlOperator with data from task: extract_chanel_data_task
[2023-10-05T15:35:05.315+0000] {logging_mixin.py:151} INFO - /home/***/youtube_starbucks_details.csv
[2023-10-05T15:35:05.320+0000] {sql.py:274} INFO - Executing: CREATE TABLE  IF NOT EXISTS organization_table(id INT AUTO_INCREMENT PRIMARY KEY, social_media_platform VARCHAR(255),description TEXT, display_name VARCHAR(255),image VARCHAR(255),subscribers INT,title VARCHAR(255),url VARCHAR(255))
[2023-10-05T15:35:05.689+0000] {base.py:73} INFO - Using connection ID 'mysql_connection' for task execution.
[2023-10-05T15:35:05.710+0000] {base.py:73} INFO - Using connection ID 'mysql_connection' for task execution.
[2023-10-05T15:35:05.738+0000] {sql.py:418} INFO - Running statement: CREATE TABLE  IF NOT EXISTS organization_table(id INT AUTO_INCREMENT PRIMARY KEY, social_media_platform VARCHAR(255),description TEXT, display_name VARCHAR(255),image VARCHAR(255),subscribers INT,title VARCHAR(255),url VARCHAR(255)), parameters: None
[2023-10-05T15:35:05.753+0000] {sql.py:427} INFO - Rows affected: 0
[2023-10-05T15:35:05.791+0000] {logging_mixin.py:151} INFO - mysql_connection
[2023-10-05T15:35:05.883+0000] {logging_mixin.py:151} INFO -              title               display_name  ...  description image
0  Starbucks Music  @starbucksmusiccollection  ...          NaN   NaN

[1 rows x 6 columns]
[2023-10-05T15:35:05.885+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/starbucks_data_table_operator.py", line 32, in execute
    self.intermediate_ingestion(context, starbucks_data_csv)
  File "/opt/airflow/plugins/starbucks_data_table_operator.py", line 62, in intermediate_ingestion
    df.to_sql(con=engine, name=self.table_name, if_exists='extend', index=False , chunksize=3000)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 2878, in to_sql
    return sql.to_sql(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 759, in to_sql
    raise ValueError(f"'{if_exists}' is not valid for if_exists")
ValueError: 'extend' is not valid for if_exists
[2023-10-05T15:35:05.899+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=YouTube_starbucks_Dag, task_id=save_starbucks_task, execution_date=20231005T153349, start_date=20231005T153504, end_date=20231005T153505
[2023-10-05T15:35:05.921+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 115 for task save_starbucks_task ('extend' is not valid for if_exists; 383)
[2023-10-05T15:35:05.980+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-05T15:35:06.005+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
