[2023-10-04T03:12:45.962+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Reddit_Post_Dag.data_transformation_task manual__2023-10-04T03:11:34.617676+00:00 [queued]>
[2023-10-04T03:12:45.978+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Reddit_Post_Dag.data_transformation_task manual__2023-10-04T03:11:34.617676+00:00 [queued]>
[2023-10-04T03:12:45.979+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-10-04T03:12:45.998+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): data_transformation_task> on 2023-10-04 03:11:34.617676+00:00
[2023-10-04T03:12:46.006+0000] {standard_task_runner.py:57} INFO - Started process 668 to run task
[2023-10-04T03:12:46.012+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Reddit_Post_Dag', 'data_transformation_task', 'manual__2023-10-04T03:11:34.617676+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/reddit_post_dag.py', '--cfg-path', '/tmp/tmpo04k3y4b']
[2023-10-04T03:12:46.018+0000] {standard_task_runner.py:85} INFO - Job 29: Subtask data_transformation_task
[2023-10-04T03:12:46.106+0000] {task_command.py:415} INFO - Running <TaskInstance: Reddit_Post_Dag.data_transformation_task manual__2023-10-04T03:11:34.617676+00:00 [running]> on host 119fbdffdc04
[2023-10-04T03:12:46.242+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Reddit_Post_Dag' AIRFLOW_CTX_TASK_ID='data_transformation_task' AIRFLOW_CTX_EXECUTION_DATE='2023-10-04T03:11:34.617676+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-04T03:11:34.617676+00:00'
[2023-10-04T03:12:46.245+0000] {logging_mixin.py:151} INFO - An error occurred in initial_data_transformation: name 'context' is not defined
[2023-10-04T03:12:46.247+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/plugins/data_transformation.py", line 47, in reddit_data_transformation
    raise e
  File "/opt/airflow/plugins/data_transformation.py", line 8, in reddit_data_transformation
    reddit_post_csv = context['task_instance'].xcom_pull(key='reddit_post_raw_data', task_ids=['extract_post_task'])[0]
NameError: name 'context' is not defined
[2023-10-04T03:12:46.270+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Reddit_Post_Dag, task_id=data_transformation_task, execution_date=20231004T031134, start_date=20231004T031245, end_date=20231004T031246
[2023-10-04T03:12:46.293+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 29 for task data_transformation_task (name 'context' is not defined; 668)
[2023-10-04T03:12:46.349+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-04T03:12:46.383+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
