[2023-10-05T09:50:05.736+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: YouTube_Post_Dag.data_transformation_task manual__2023-10-05T09:49:54.639470+00:00 [queued]>
[2023-10-05T09:50:05.755+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: YouTube_Post_Dag.data_transformation_task manual__2023-10-05T09:49:54.639470+00:00 [queued]>
[2023-10-05T09:50:05.756+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-10-05T09:50:05.777+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): data_transformation_task> on 2023-10-05 09:49:54.639470+00:00
[2023-10-05T09:50:05.795+0000] {standard_task_runner.py:57} INFO - Started process 157 to run task
[2023-10-05T09:50:05.806+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'YouTube_Post_Dag', 'data_transformation_task', 'manual__2023-10-05T09:49:54.639470+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/youTube_video_data_dag.py', '--cfg-path', '/tmp/tmpjp2omh5b']
[2023-10-05T09:50:05.813+0000] {standard_task_runner.py:85} INFO - Job 84: Subtask data_transformation_task
[2023-10-05T09:50:05.893+0000] {task_command.py:415} INFO - Running <TaskInstance: YouTube_Post_Dag.data_transformation_task manual__2023-10-05T09:49:54.639470+00:00 [running]> on host bdf8a93b58be
[2023-10-05T09:50:06.038+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='YouTube_Post_Dag' AIRFLOW_CTX_TASK_ID='data_transformation_task' AIRFLOW_CTX_EXECUTION_DATE='2023-10-05T09:49:54.639470+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-05T09:49:54.639470+00:00'
[2023-10-05T09:50:06.062+0000] {logging_mixin.py:151} INFO - An error occurred in initial_data_transformation: 0
[2023-10-05T09:50:06.063+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/plugins/youTube_data_transformation.py", line 30, in youTube_data_transformation
    raise e
  File "/opt/airflow/plugins/youTube_data_transformation.py", line 7, in youTube_data_transformation
    youtube_post_csv = ti.xcom_pull(key='youTube_video_raw_data', task_ids=['extract_post_task'])[0]
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 794, in __getitem__
    raise IndexError(key) from None
IndexError: 0
[2023-10-05T09:50:06.335+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=YouTube_Post_Dag, task_id=data_transformation_task, execution_date=20231005T094954, start_date=20231005T095005, end_date=20231005T095006
[2023-10-05T09:50:06.353+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 84 for task data_transformation_task (0; 157)
[2023-10-05T09:50:06.419+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-05T09:50:06.459+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
