[2023-10-05T09:49:13.220+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: YouTube_Post_Dag.processed_data_insert_task manual__2023-10-05T09:49:03.845914+00:00 [queued]>
[2023-10-05T09:49:13.245+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: YouTube_Post_Dag.processed_data_insert_task manual__2023-10-05T09:49:03.845914+00:00 [queued]>
[2023-10-05T09:49:13.249+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-10-05T09:49:13.287+0000] {taskinstance.py:1382} INFO - Executing <Task(YouTubeProcessDataTableOperator): processed_data_insert_task> on 2023-10-05 09:49:03.845914+00:00
[2023-10-05T09:49:13.320+0000] {standard_task_runner.py:57} INFO - Started process 127 to run task
[2023-10-05T09:49:13.497+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'YouTube_Post_Dag', 'processed_data_insert_task', 'manual__2023-10-05T09:49:03.845914+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/youTube_video_data_dag.py', '--cfg-path', '/tmp/tmpdc91hram']
[2023-10-05T09:49:13.570+0000] {standard_task_runner.py:85} INFO - Job 80: Subtask processed_data_insert_task
[2023-10-05T09:49:14.175+0000] {task_command.py:415} INFO - Running <TaskInstance: YouTube_Post_Dag.processed_data_insert_task manual__2023-10-05T09:49:03.845914+00:00 [running]> on host bdf8a93b58be
[2023-10-05T09:49:14.840+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='YouTube_Post_Dag' AIRFLOW_CTX_TASK_ID='processed_data_insert_task' AIRFLOW_CTX_EXECUTION_DATE='2023-10-05T09:49:03.845914+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-05T09:49:03.845914+00:00'
[2023-10-05T09:49:14.848+0000] {youTube_process_data_table_operator.py:27} INFO - Executing CustomMySqlOperator with data from task: data_transformation_task
[2023-10-05T09:49:14.909+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/youTube_process_data_table_operator.py", line 28, in execute
    reddit_post_csv = context['task_instance'].xcom_pull(key='reddit_post_process_data', task_ids=['data_transformation_task'])[0]
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 794, in __getitem__
    raise IndexError(key) from None
IndexError: 0
[2023-10-05T09:49:14.932+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=YouTube_Post_Dag, task_id=processed_data_insert_task, execution_date=20231005T094903, start_date=20231005T094913, end_date=20231005T094914
[2023-10-05T09:49:14.983+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 80 for task processed_data_insert_task (0; 127)
[2023-10-05T09:49:15.015+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-05T09:49:15.097+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
