[2023-10-05T06:46:46.707+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Reddit_Post_Comment_Dag.sentiment_analysis_task manual__2023-10-05T06:44:43.227282+00:00 [queued]>
[2023-10-05T06:46:46.721+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Reddit_Post_Comment_Dag.sentiment_analysis_task manual__2023-10-05T06:44:43.227282+00:00 [queued]>
[2023-10-05T06:46:46.723+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-10-05T06:46:46.741+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): sentiment_analysis_task> on 2023-10-05 06:44:43.227282+00:00
[2023-10-05T06:46:46.751+0000] {standard_task_runner.py:57} INFO - Started process 149 to run task
[2023-10-05T06:46:46.759+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Reddit_Post_Comment_Dag', 'sentiment_analysis_task', 'manual__2023-10-05T06:44:43.227282+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/reddit_post_comment_dag.py', '--cfg-path', '/tmp/tmpul3narvl']
[2023-10-05T06:46:46.765+0000] {standard_task_runner.py:85} INFO - Job 68: Subtask sentiment_analysis_task
[2023-10-05T06:46:46.856+0000] {task_command.py:415} INFO - Running <TaskInstance: Reddit_Post_Comment_Dag.sentiment_analysis_task manual__2023-10-05T06:44:43.227282+00:00 [running]> on host 44d08be4c1e6
[2023-10-05T06:46:46.991+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Reddit_Post_Comment_Dag' AIRFLOW_CTX_TASK_ID='sentiment_analysis_task' AIRFLOW_CTX_EXECUTION_DATE='2023-10-05T06:44:43.227282+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-05T06:44:43.227282+00:00'
[2023-10-05T06:46:47.008+0000] {logging_mixin.py:151} INFO - An error occurred in initial_data_transformation: 0
[2023-10-05T06:46:47.010+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/plugins/sentiment_analysis.py", line 66, in update_polarity
    raise e
  File "/opt/airflow/plugins/sentiment_analysis.py", line 11, in update_polarity
    reddit_comment_csv = ti.xcom_pull(key='reddit_post_comment_raw_data', task_ids=['extract_post_task'])[0]
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 794, in __getitem__
    raise IndexError(key) from None
IndexError: 0
[2023-10-05T06:46:47.020+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Reddit_Post_Comment_Dag, task_id=sentiment_analysis_task, execution_date=20231005T064443, start_date=20231005T064646, end_date=20231005T064647
[2023-10-05T06:46:47.038+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 68 for task sentiment_analysis_task (0; 149)
[2023-10-05T06:46:47.092+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-05T06:46:47.120+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
