[2023-10-03T14:49:03.130+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Reddit_Post_Dag.extract_post_task manual__2023-10-03T14:48:59.438533+00:00 [queued]>
[2023-10-03T14:49:03.147+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Reddit_Post_Dag.extract_post_task manual__2023-10-03T14:48:59.438533+00:00 [queued]>
[2023-10-03T14:49:03.149+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-10-03T14:49:03.169+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract_post_task> on 2023-10-03 14:48:59.438533+00:00
[2023-10-03T14:49:03.177+0000] {standard_task_runner.py:57} INFO - Started process 161 to run task
[2023-10-03T14:49:03.183+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Reddit_Post_Dag', 'extract_post_task', 'manual__2023-10-03T14:48:59.438533+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/reddit_post_dag.py', '--cfg-path', '/tmp/tmpyd8ogtst']
[2023-10-03T14:49:03.190+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask extract_post_task
[2023-10-03T14:49:03.273+0000] {task_command.py:415} INFO - Running <TaskInstance: Reddit_Post_Dag.extract_post_task manual__2023-10-03T14:48:59.438533+00:00 [running]> on host a82955aebbba
[2023-10-03T14:49:03.420+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Reddit_Post_Dag' AIRFLOW_CTX_TASK_ID='extract_post_task' AIRFLOW_CTX_EXECUTION_DATE='2023-10-03T14:48:59.438533+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-03T14:48:59.438533+00:00'
[2023-10-03T14:49:25.185+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/plugins/reddit_data_extractor.py", line 51, in extract_post_data
    topics_data.to_csv(csv_file_path, index=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 3772, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/format.py", line 1186, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/csvs.py", line 240, in save
    with get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 737, in get_handle
    check_parent_directory(str(handle))
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 600, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: 'data/raw'
[2023-10-03T14:49:25.206+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=Reddit_Post_Dag, task_id=extract_post_task, execution_date=20231003T144859, start_date=20231003T144903, end_date=20231003T144925
[2023-10-03T14:49:25.227+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task extract_post_task (Cannot save file into a non-existent directory: 'data/raw'; 161)
[2023-10-03T14:49:25.247+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-03T14:49:25.271+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
