[2023-10-05T09:49:13.273+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: YouTube_Post_Dag.data_transformation_task manual__2023-10-05T09:49:03.845914+00:00 [queued]>
[2023-10-05T09:49:13.300+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: YouTube_Post_Dag.data_transformation_task manual__2023-10-05T09:49:03.845914+00:00 [queued]>
[2023-10-05T09:49:13.302+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-10-05T09:49:13.350+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): data_transformation_task> on 2023-10-05 09:49:03.845914+00:00
[2023-10-05T09:49:13.374+0000] {standard_task_runner.py:57} INFO - Started process 128 to run task
[2023-10-05T09:49:13.569+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'YouTube_Post_Dag', 'data_transformation_task', 'manual__2023-10-05T09:49:03.845914+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/youTube_video_data_dag.py', '--cfg-path', '/tmp/tmpny7kkgej']
[2023-10-05T09:49:13.691+0000] {standard_task_runner.py:85} INFO - Job 81: Subtask data_transformation_task
[2023-10-05T09:49:14.287+0000] {task_command.py:415} INFO - Running <TaskInstance: YouTube_Post_Dag.data_transformation_task manual__2023-10-05T09:49:03.845914+00:00 [running]> on host bdf8a93b58be
[2023-10-05T09:49:14.870+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='YouTube_Post_Dag' AIRFLOW_CTX_TASK_ID='data_transformation_task' AIRFLOW_CTX_EXECUTION_DATE='2023-10-05T09:49:03.845914+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-05T09:49:03.845914+00:00'
[2023-10-05T09:49:14.890+0000] {logging_mixin.py:151} INFO - An error occurred in initial_data_transformation: 0
[2023-10-05T09:49:14.894+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/plugins/youTube_data_transformation.py", line 30, in youTube_data_transformation
    raise e
  File "/opt/airflow/plugins/youTube_data_transformation.py", line 7, in youTube_data_transformation
    youtube_post_csv = ti.xcom_pull(key='youTube_video_raw_data', task_ids=['extract_post_task'])[0]
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 794, in __getitem__
    raise IndexError(key) from None
IndexError: 0
[2023-10-05T09:49:14.947+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=YouTube_Post_Dag, task_id=data_transformation_task, execution_date=20231005T094903, start_date=20231005T094913, end_date=20231005T094914
[2023-10-05T09:49:15.002+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 81 for task data_transformation_task (0; 128)
[2023-10-05T09:49:15.055+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-05T09:49:15.126+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
